### ISSUE TITLE
Publisher for the change log in a build page

### ISSUE THREAD

**Issue by dcoraboeuf** [jenkinsci/ontrack-plugin#4]
Have a publisher which creates an action which displays an Ontrack change log in the build page.

Parameters:
- project name
- branch name
- the two build boundaries are determined by a parameter value (`VERSION` by default, but can be configured) on the:
  - current build
  - previous build

The change log is computed between the two builds.

If the `Distinct builds` option is checked, the change log is computed for each build interval.
- [x] Displays the build boundaries on top of the change log
- [x] Link to the full details: commits, issues and files
- [x] Case when no build difference - no change log
- [x] No issue section when no issue
- [x] Link to the issue
- [x] Link to the Ontrack change log page - this would need Ontrack to provide links to the pages in the resource links - see nemerosa/ontrack#275
- [x] Option to split the change logs per build - needs for Ontrack to provide such a query - see nemerosa/ontrack#276
- [x] Case where builds are not found

**Comment by dcoraboeuf** [comment]
* [ ] Depends on nemerosa/ontrack#274 issue to be solved.

**Comment by dcoraboeuf** [comment]
Page link available in prerelease `feature-275-page-link-aab1758` (waiting for `0.10.0` to be available)

**Comment by dcoraboeuf** [comment]
Waiting for release of 0.10.0 of Ontrack before reintegrating the branch.
